{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitor-operator.fullname" . }}-manager-role
  labels:
    {{- include "monitor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cillian.website
  resources:
  - monitorstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cillian.website
  resources:
  - monitorstacks/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.cillian.website
  resources:
  - monitorstacks/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "monitor-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "monitor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "monitor-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "monitor-operator.serviceAccountName" . }}
  namespace: {{ include "monitor-operator.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitor-operator.fullname" . }}-leader-election-role
  namespace: {{ include "monitor-operator.namespace" . }}
  labels:
    {{- include "monitor-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitor-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "monitor-operator.namespace" . }}
  labels:
    {{- include "monitor-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "monitor-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "monitor-operator.serviceAccountName" . }}
  namespace: {{ include "monitor-operator.namespace" . }}
{{- end }}