{{- if .Values.backend.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cilikube.fullname" . }}-backend
  labels:
    {{- include "cilikube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cilikube.selectorLabels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.frontend.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cilikube.fullname" . }}-frontend
  labels:
    {{- include "cilikube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
      {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "cilikube.selectorLabels" . | nindent 4 }}
{{- end }}