---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor-operator.fullname" . }}-controller-manager
  namespace: {{ include "monitor-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    {{- include "monitor-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    {{- include "monitor-operator.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitor-operator.fullname" . }}-metrics
  namespace: {{ include "monitor-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    {{- include "monitor-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.targetPort }}
  selector:
    {{- include "monitor-operator.selectorLabels" . | nindent 4 }}
{{- end }}